# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  emacs-copilot = {
    pname = "emacs-copilot";
    version = "4f51b3c21c42756d09ee17011201ea7d6e18ff69";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "4f51b3c21c42756d09ee17011201ea7d6e18ff69";
      fetchSubmodules = false;
      sha256 = "sha256-5nB+skW0yjKvLUkDcwFJGSsCcRPZnJ44KoiTJno2iRM=";
    };
    date = "2025-06-30";
  };
}
