# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  dpp-ext-installer = {
    pname = "dpp-ext-installer";
    version = "25ed2c4c0c7415950476be4a8e7e0c541127cefa";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-ext-installer";
      rev = "25ed2c4c0c7415950476be4a8e7e0c541127cefa";
      fetchSubmodules = false;
      sha256 = "sha256-LnYjCg3DTq74wgVO19xAe/EdonJeiZUufgdTrOAV4HY=";
    };
    date = "2025-09-12";
  };
  dpp-ext-lazy = {
    pname = "dpp-ext-lazy";
    version = "b723904ebca49c51f3390b4cd602396c27fbb7b2";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-ext-lazy";
      rev = "b723904ebca49c51f3390b4cd602396c27fbb7b2";
      fetchSubmodules = false;
      sha256 = "sha256-Tre8NvXcmlRS0nUpD0fdvl/fa4eL7jtA3L6JWjbfOQQ=";
    };
    date = "2025-09-11";
  };
  dpp-ext-toml = {
    pname = "dpp-ext-toml";
    version = "9a441896eebb09ca5f9b93fec79d094799ae3cde";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-ext-toml";
      rev = "9a441896eebb09ca5f9b93fec79d094799ae3cde";
      fetchSubmodules = false;
      sha256 = "sha256-txtUBfy9FcFQt/TWWD1p+Z8vVhUyolxtMpwfuvJzv8g=";
    };
    date = "2025-08-30";
  };
  dpp-protocol-git = {
    pname = "dpp-protocol-git";
    version = "836be06310abb1237366fd2d2220c86857c44668";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-protocol-git";
      rev = "836be06310abb1237366fd2d2220c86857c44668";
      fetchSubmodules = false;
      sha256 = "sha256-hgtDoii32mDnUTPDLVSJh4GjKdHUbg75131598GZ7jI=";
    };
    date = "2025-09-11";
  };
  dpp-vim = {
    pname = "dpp-vim";
    version = "ebf6e6d8f962400b3289b5b83d114af0d6ac04ea";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp.vim";
      rev = "ebf6e6d8f962400b3289b5b83d114af0d6ac04ea";
      fetchSubmodules = false;
      sha256 = "sha256-KTZM9N0gPiJtIx71N0txySt4VEnfxpAHqufldBPQqAI=";
    };
    date = "2025-09-11";
  };
  emacs-copilot = {
    pname = "emacs-copilot";
    version = "4f51b3c21c42756d09ee17011201ea7d6e18ff69";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "4f51b3c21c42756d09ee17011201ea7d6e18ff69";
      fetchSubmodules = false;
      sha256 = "sha256-5nB+skW0yjKvLUkDcwFJGSsCcRPZnJ44KoiTJno2iRM=";
    };
    date = "2025-06-30";
  };
  emacs-yatex = {
    pname = "emacs-yatex";
    version = "dd7cfad4cd0409b5e0eb05e90077de5a225185fa";
    src = fetchFromGitHub {
      owner = "hiroseyuuji";
      repo = "yatex";
      rev = "dd7cfad4cd0409b5e0eb05e90077de5a225185fa";
      fetchSubmodules = false;
      sha256 = "sha256-rlZJPP+Z0S2+dNhuiXf+NCX2rbfJFW27UuGT9PidzNs=";
    };
    date = "2025-02-24";
  };
}
