# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  emacs-copilot = {
    pname = "emacs-copilot";
    version = "4f51b3c21c42756d09ee17011201ea7d6e18ff69";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "4f51b3c21c42756d09ee17011201ea7d6e18ff69";
      fetchSubmodules = false;
      sha256 = "sha256-5nB+skW0yjKvLUkDcwFJGSsCcRPZnJ44KoiTJno2iRM=";
    };
    date = "2025-06-30";
  };
  emacs-yatex = {
    pname = "emacs-yatex";
    version = "2e1104f62b98cb9e73f4836a267b5c8271fb5b9b";
    src = fetchFromGitHub {
      owner = "emacsmirror";
      repo = "yatex";
      rev = "2e1104f62b98cb9e73f4836a267b5c8271fb5b9b";
      fetchSubmodules = false;
      sha256 = "sha256-rlZJPP+Z0S2+dNhuiXf+NCX2rbfJFW27UuGT9PidzNs=";
    };
    date = "2025-02-24";
  };
}
