version: 2
updates:
  - package-ecosystem: npm
    directory: /.config/nix
    schedule:
      interval: daily
    target-branch: main
  - package-ecosystem: github-actions
    directory: /config/nix
    schedule:
      interval: daily
