local pick = require("mini.pick")
local extra = require("mini.extra")
local files = require("mini.files")

pick.setup({})
extra.setup({})
vim.ui.select = pick.ui_select

local opt = { noremap = true, silent = true }

local function buffer_lines(query)
	if query ~= nil and query ~= "" then
		vim.schedule(function()
			if pick.is_picker_active() then
				pick.set_picker_query({ query })
			end
		end)
	end
	extra.pickers.buf_lines({ scope = "current", preserve_order = false })
end

vim.keymap.set("n", "<Leader>ff", function()
	pick.builtin.files()
end, opt)
vim.keymap.set("n", "<leader>h", function()
	pick.builtin.help()
end, opt)
vim.keymap.set("n", "<leader>fr", function()
	pick.builtin.grep_live()
end, opt)
vim.keymap.set("n", "<leader>lr", function()
	extra.pickers.lsp({ scope = "references" })
end, opt)
vim.keymap.set("n", "<leader>ld", function()
	extra.pickers.diagnostic({ scope = "current" })
end, opt)
vim.keymap.set("n", "<leader>ls", function()
	extra.pickers.lsp({ scope = "document_symbol" })
end, opt)
vim.keymap.set("n", "<leader>ic", function()
	vim.lsp.buf.incoming_calls()
end, opt)
vim.keymap.set("n", "<leader>oc", function()
	vim.lsp.buf.outgoing_calls()
end, opt)
vim.keymap.set("n", "<Leader>sb", function()
	pick.builtin.buffers()
end, opt)
vim.keymap.set("n", "/", function()
	buffer_lines()
end, opt)
vim.keymap.set("n", "*", function()
	buffer_lines(vim.fn.expand("<cword>"))
end, opt)
vim.keymap.set("n", "<leader>k", function()
	extra.pickers.keymaps()
end, opt)
vim.keymap.set("n", "<leader>dp", "<cmd>DepsUpdate<cr>", opt)
vim.keymap.set("n", "n", function()
	pick.builtin.resume()
end, opt)
vim.keymap.set("n", "<leader>e", function()
	extra.pickers.diagnostic({ scope = "current" })
end, opt)
vim.keymap.set("n", "<leader>sf", function()
	local path = vim.api.nvim_buf_get_name(0)
	if path == "" then path = nil end
	files.open(path)
end, opt)
