# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dpp-ext-installer = {
    pname = "dpp-ext-installer";
    version = "25ed2c4c0c7415950476be4a8e7e0c541127cefa";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-ext-installer";
      rev = "25ed2c4c0c7415950476be4a8e7e0c541127cefa";
      fetchSubmodules = false;
      sha256 = "sha256-LnYjCg3DTq74wgVO19xAe/EdonJeiZUufgdTrOAV4HY=";
    };
    date = "2025-09-12";
  };
  dpp-ext-lazy = {
    pname = "dpp-ext-lazy";
    version = "e19c8e01398c3822a7d8b7235ae5d1608923dd10";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-ext-lazy";
      rev = "e19c8e01398c3822a7d8b7235ae5d1608923dd10";
      fetchSubmodules = false;
      sha256 = "sha256-f+8XoYou73ySIl5j82+dP9or3ebyjlUyZOErlYOCQPc=";
    };
    date = "2025-10-06";
  };
  dpp-ext-toml = {
    pname = "dpp-ext-toml";
    version = "9a441896eebb09ca5f9b93fec79d094799ae3cde";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-ext-toml";
      rev = "9a441896eebb09ca5f9b93fec79d094799ae3cde";
      fetchSubmodules = false;
      sha256 = "sha256-txtUBfy9FcFQt/TWWD1p+Z8vVhUyolxtMpwfuvJzv8g=";
    };
    date = "2025-08-30";
  };
  dpp-protocol-git = {
    pname = "dpp-protocol-git";
    version = "dd6dddfaa0bdc3cccde41316bcb9a24dbc701040";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-protocol-git";
      rev = "dd6dddfaa0bdc3cccde41316bcb9a24dbc701040";
      fetchSubmodules = false;
      sha256 = "sha256-qaLbB+MP9C+9VpdbZ01HLCzSa1NhaG7Kd1nxrc3bAVs=";
    };
    date = "2025-09-23";
  };
  dpp-vim = {
    pname = "dpp-vim";
    version = "eff3ee4e7b0b9b4dce889914271a3f1cde591e4a";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp.vim";
      rev = "eff3ee4e7b0b9b4dce889914271a3f1cde591e4a";
      fetchSubmodules = false;
      sha256 = "sha256-YqSwpgyN4QHa59yLg8PZF03e7kuHF/ilyqHhePltroI=";
    };
    date = "2025-09-24";
  };
  emacs-copilot = {
    pname = "emacs-copilot";
    version = "6a2ad80489b8a0d021df95293eb7ac370aea140b";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "6a2ad80489b8a0d021df95293eb7ac370aea140b";
      fetchSubmodules = false;
      sha256 = "sha256-aiVRefuH4jpAtTgMMDa7jI0Yy08J4+fV59f8nd7vT7g=";
    };
    date = "2025-09-16";
  };
  emacs-yaml-mode = {
    pname = "emacs-yaml-mode";
    version = "d91f878729312a6beed77e6637c60497c5786efa";
    src = fetchFromGitHub {
      owner = "yoshiki";
      repo = "yaml-mode";
      rev = "d91f878729312a6beed77e6637c60497c5786efa";
      fetchSubmodules = false;
      sha256 = "sha256-BxIHvMOEWwW0C+lWGnxhvqtpK2bVHA7pLBaut3LpsmQ=";
    };
    date = "2024-10-03";
  };
  emacs-yatex = {
    pname = "emacs-yatex";
    version = "dd7cfad4cd0409b5e0eb05e90077de5a225185fa";
    src = fetchFromGitHub {
      owner = "hiroseyuuji";
      repo = "yatex";
      rev = "dd7cfad4cd0409b5e0eb05e90077de5a225185fa";
      fetchSubmodules = false;
      sha256 = "sha256-rlZJPP+Z0S2+dNhuiXf+NCX2rbfJFW27UuGT9PidzNs=";
    };
    date = "2025-02-24";
  };
  yaskkserv2 = {
    pname = "yaskkserv2";
    version = "0.1.7";
    src = fetchFromGitHub {
      owner = "wachikun";
      repo = "yaskkserv2";
      rev = "0.1.7";
      fetchSubmodules = false;
      sha256 = "sha256-bF8OHP6nvGhxXNvvnVCuOVFarK/n7WhGRktRN4X5ZjE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./yaskkserv2-0.1.7/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
}
