# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cargo-compete = {
    pname = "cargo-compete";
    version = "v0.10.7";
    src = fetchFromGitHub {
      owner = "qryxip";
      repo = "cargo-compete";
      rev = "v0.10.7";
      fetchSubmodules = false;
      sha256 = "sha256-qlRVHSUVOqdTx4H3pE19Fy634742veTisHm6IqfKBUQ=";
    };
  };
  dpp-ext-installer = {
    pname = "dpp-ext-installer";
    version = "e86a8e1b83be82cd6e71fb49d9b569feccb925a9";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-ext-installer";
      rev = "e86a8e1b83be82cd6e71fb49d9b569feccb925a9";
      fetchSubmodules = false;
      sha256 = "sha256-CLlRfCBTydRy8Vke3iFudf2AAV/KV7Bx5/vbUnHn8XE=";
    };
    date = "2026-02-02";
  };
  dpp-ext-lazy = {
    pname = "dpp-ext-lazy";
    version = "51ad5e2223ad2ca5c3f0c80a0f1063fbacb1fd4e";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-ext-lazy";
      rev = "51ad5e2223ad2ca5c3f0c80a0f1063fbacb1fd4e";
      fetchSubmodules = false;
      sha256 = "sha256-tNova2vZiJYEdagzBHtJ9x/HN7suXXZlYxbm3ifvtU0=";
    };
    date = "2026-03-07";
  };
  dpp-ext-toml = {
    pname = "dpp-ext-toml";
    version = "9a441896eebb09ca5f9b93fec79d094799ae3cde";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-ext-toml";
      rev = "9a441896eebb09ca5f9b93fec79d094799ae3cde";
      fetchSubmodules = false;
      sha256 = "sha256-txtUBfy9FcFQt/TWWD1p+Z8vVhUyolxtMpwfuvJzv8g=";
    };
    date = "2025-08-30";
  };
  dpp-protocol-git = {
    pname = "dpp-protocol-git";
    version = "f92120460b797d2e4707f3bcd18080a27d7bd026";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp-protocol-git";
      rev = "f92120460b797d2e4707f3bcd18080a27d7bd026";
      fetchSubmodules = false;
      sha256 = "sha256-jKK5wOpQizG2BqEJbLuVqdZkMzy3gF2XlD0ZUb8eTiM=";
    };
    date = "2026-02-02";
  };
  dpp-vim = {
    pname = "dpp-vim";
    version = "16ce424b8512e624bd88ce4dc0cf5728d1f6b0ed";
    src = fetchFromGitHub {
      owner = "Shougo";
      repo = "dpp.vim";
      rev = "16ce424b8512e624bd88ce4dc0cf5728d1f6b0ed";
      fetchSubmodules = false;
      sha256 = "sha256-6a+qXgmo40E/cSs98ZFIlrada+dEQKMR8YFa6sWAQcg=";
    };
    date = "2026-02-22";
  };
  emacs-acp = {
    pname = "emacs-acp";
    version = "863f2d62c4b4da8b229581be42d490a7403b2eb1";
    src = fetchFromGitHub {
      owner = "xenodium";
      repo = "acp.el";
      rev = "863f2d62c4b4da8b229581be42d490a7403b2eb1";
      fetchSubmodules = false;
      sha256 = "sha256-JblbafhQlCCyFq82wXL09P2gRldrSxXdlTkIeytGISE=";
    };
    date = "2026-03-20";
  };
  emacs-dmacro = {
    pname = "emacs-dmacro";
    version = "c714fcdbac3ae57fcc8ff3db94b0e5aededc7468";
    src = fetchFromGitHub {
      owner = "emacs-jp";
      repo = "dmacro";
      rev = "c714fcdbac3ae57fcc8ff3db94b0e5aededc7468";
      fetchSubmodules = false;
      sha256 = "sha256-gXUr56grxz6+OvQW7YE+dAXDkGyDq0JQclCvKNNiu0Y=";
    };
    date = "2024-10-27";
  };
  emacs-hide-lines = {
    pname = "emacs-hide-lines";
    version = "803443035c7feb85ea1ad83e49629c54dfc48e8d";
    src = fetchFromGitHub {
      owner = "vapniks";
      repo = "hide-lines";
      rev = "803443035c7feb85ea1ad83e49629c54dfc48e8d";
      fetchSubmodules = false;
      sha256 = "sha256-duzCjFVY5Mq3GBz0udPjFgP2otL2bSnyViBStMJictk=";
    };
    date = "2025-05-23";
  };
  emacs-instant-maximized-window = {
    pname = "emacs-instant-maximized-window";
    version = "e6b82419bf9c154df881c72c5800bbd43887ec0d";
    src = fetchFromGitHub {
      owner = "blue0513";
      repo = "instant-maximized-window";
      rev = "e6b82419bf9c154df881c72c5800bbd43887ec0d";
      fetchSubmodules = false;
      sha256 = "sha256-UEvyC0utnPuBmoCBljU/M/ytLUdFCQ881tC8Qba8vA8=";
    };
    date = "2018-05-28";
  };
  emacs-kuro = {
    pname = "emacs-kuro";
    version = "634ee8eb64cd95e4400c6993f63389606886b044";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "kuro";
      rev = "634ee8eb64cd95e4400c6993f63389606886b044";
      fetchSubmodules = false;
      sha256 = "sha256-24cAyAiojDQTyAZMYav6fm53BGYlJnEAkQrtbNngTfc=";
    };
    date = "2026-03-22";
  };
  emacs-nano-modeline = {
    pname = "emacs-nano-modeline";
    version = "04676d57a1e602123a593836745a744d1b2028fb";
    src = fetchFromGitHub {
      owner = "rougier";
      repo = "nano-modeline";
      rev = "04676d57a1e602123a593836745a744d1b2028fb";
      fetchSubmodules = false;
      sha256 = "sha256-CoADZ4L4JpoF3JRMb793z2nAq8s1VE3uqb3gqFD7IOA=";
    };
    date = "2024-04-29";
  };
  emacs-nskk = {
    pname = "emacs-nskk";
    version = "4bf42c8e19bc4a9242b8acc8a7445a5df84d1140";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "nskk.el";
      rev = "4bf42c8e19bc4a9242b8acc8a7445a5df84d1140";
      fetchSubmodules = false;
      sha256 = "sha256-ptbq0cKocZuUucoLRTSFAq90jFZS3CpO8FxQSj3S1sE=";
    };
    date = "2026-03-22";
  };
  emacs-org-hyperscheduler = {
    pname = "emacs-org-hyperscheduler";
    version = "f40e3df279452dc0cb8506de3bfb6acbf2df79c1";
    src = fetchFromGitHub {
      owner = "dmitrym0";
      repo = "org-hyperscheduler";
      rev = "f40e3df279452dc0cb8506de3bfb6acbf2df79c1";
      fetchSubmodules = false;
      sha256 = "sha256-/KpmgpHET+5/GDCQwkEQxssX4kkzhZbJ+wxbUAoppIA=";
    };
    date = "2025-07-16";
  };
  emacs-typst-ts-mode = {
    pname = "emacs-typst-ts-mode";
    version = "aee8ff090cff6f39a70ac2c9035b1eb2b69924d7";
    src = fetchFromGitHub {
      owner = "Ziqi-Yang";
      repo = "typst-ts-mode";
      rev = "aee8ff090cff6f39a70ac2c9035b1eb2b69924d7";
      fetchSubmodules = false;
      sha256 = "sha256-oZ4uq87PeqXGIy8Dmx7ppGzrxDhiJEGOH8nXerZ03ik=";
    };
    date = "2025-01-18";
  };
  emacs-yaml-mode = {
    pname = "emacs-yaml-mode";
    version = "d91f878729312a6beed77e6637c60497c5786efa";
    src = fetchFromGitHub {
      owner = "yoshiki";
      repo = "yaml-mode";
      rev = "d91f878729312a6beed77e6637c60497c5786efa";
      fetchSubmodules = false;
      sha256 = "sha256-BxIHvMOEWwW0C+lWGnxhvqtpK2bVHA7pLBaut3LpsmQ=";
    };
    date = "2024-10-03";
  };
  emacs-yatex = {
    pname = "emacs-yatex";
    version = "dd7cfad4cd0409b5e0eb05e90077de5a225185fa";
    src = fetchFromGitHub {
      owner = "hiroseyuuji";
      repo = "yatex";
      rev = "dd7cfad4cd0409b5e0eb05e90077de5a225185fa";
      fetchSubmodules = false;
      sha256 = "sha256-rlZJPP+Z0S2+dNhuiXf+NCX2rbfJFW27UuGT9PidzNs=";
    };
    date = "2025-02-24";
  };
  emacs-ysnippet-capf = {
    pname = "emacs-ysnippet-capf";
    version = "f53c42a996b86fc95b96bdc2deeb58581f48c666";
    src = fetchFromGitHub {
      owner = "elken";
      repo = "yasnippet-capf";
      rev = "f53c42a996b86fc95b96bdc2deeb58581f48c666";
      fetchSubmodules = false;
      sha256 = "sha256-KWh8trHgrU+v+52cF0e1aJQ3oc9y8D25dg2UwIvKmsM=";
    };
    date = "2025-05-20";
  };
  fish-autols = {
    pname = "fish-autols";
    version = "74c52a3f66b5b9f589871c4383e7d7c2e543032c";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "fish-autols";
      rev = "74c52a3f66b5b9f589871c4383e7d7c2e543032c";
      fetchSubmodules = false;
      sha256 = "sha256-5yb6UjPu+QFsR+fe1rzYgSUczQ6olbFgILUQNTGvnf8=";
    };
    date = "2025-01-26";
  };
  fish-cdf = {
    pname = "fish-cdf";
    version = "467f549ef6f8b1d8d18a429639f87870b23eef62";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "fish-cdf";
      rev = "467f549ef6f8b1d8d18a429639f87870b23eef62";
      fetchSubmodules = false;
      sha256 = "sha256-ZA5ZLE/5w9EhT7uB1hlkj0h/C0b5WQl46PpvOz8SlSU=";
    };
    date = "2025-01-27";
  };
  fish-fzf-bd = {
    pname = "fish-fzf-bd";
    version = "fcbe9f6a75510365638dc6f790544c55ecb0ec3b";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "fish-fzf-bd";
      rev = "fcbe9f6a75510365638dc6f790544c55ecb0ec3b";
      fetchSubmodules = false;
      sha256 = "sha256-NAErU+F7CTf0wOfR1zfxw2TRBLPIHe5QDjEhyjCNLJE=";
    };
    date = "2025-01-27";
  };
  fish-gcd = {
    pname = "fish-gcd";
    version = "e42ccc3c48ecaf2a8efb8a12d7426a8a7fd077e3";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "fish-gcd";
      rev = "e42ccc3c48ecaf2a8efb8a12d7426a8a7fd077e3";
      fetchSubmodules = false;
      sha256 = "sha256-uoqU5XGdMRvhsUQ0C+0rNyaD4fJQX7gf1G6zsC5L4iU=";
    };
    date = "2025-01-25";
  };
  fish-ghq-fzf = {
    pname = "fish-ghq-fzf";
    version = "9798eadadda71c3cb43502f88cfce1f9521ee185";
    src = fetchFromGitHub {
      owner = "yuys13";
      repo = "fish-ghq-fzf";
      rev = "9798eadadda71c3cb43502f88cfce1f9521ee185";
      fetchSubmodules = false;
      sha256 = "sha256-64y5nTQsdz8Qyn0VjEtfI4FvTMjF5XVYW7yTsrkIS30=";
    };
    date = "2025-01-27";
  };
  mocword = {
    pname = "mocword";
    version = "096316545837ca70498023486390f74f6b7c8fd3";
    src = fetchFromGitHub {
      owner = "high-moctane";
      repo = "mocword";
      rev = "096316545837ca70498023486390f74f6b7c8fd3";
      fetchSubmodules = false;
      sha256 = "sha256-aDwqj9myaGRkAcVkC2upHtQT+uq/ZRk72teWz6egCsc=";
    };
    date = "2022-05-02";
  };
  yaskkserv2 = {
    pname = "yaskkserv2";
    version = "0.1.7";
    src = fetchFromGitHub {
      owner = "wachikun";
      repo = "yaskkserv2";
      rev = "0.1.7";
      fetchSubmodules = false;
      sha256 = "sha256-bF8OHP6nvGhxXNvvnVCuOVFarK/n7WhGRktRN4X5ZjE=";
    };
  };
}
