-- vim.cmd("filetype plugin indent on")
-- vim.cmd("syntax enable")

-- local MiniIcons = require("mini.icons")
-- MiniIcons.setup({})
-- MiniIcons.tweak_lsp_kind()
-- MiniIcons.mock_nvim_web_devicons()

-- require("mini.comment").setup()
-- require("mini.pairs").setup()
-- require("mini.surround").setup()
-- require("mini.ai").setup()
-- require("mini.jump").setup()
-- require("mini.diff").setup({
-- 	view = {
-- 		style = vim.go.number and "number" or "sign",
-- 	},
-- })
-- require("mini.git").setup()
-- require("mini.tabline").setup()
-- require("mini.bracketed").setup()
--
-- local miniclue = require("mini.clue")
-- miniclue.setup({
-- 	triggers = {
-- 		{ mode = { "n", "x" }, keys = "<Leader>" },
-- 		{ mode = "n", keys = "[" },
-- 		{ mode = "n", keys = "]" },
-- 		{ mode = "i", keys = "<C-x>" },
-- 		{ mode = { "n", "x" }, keys = "g" },
-- 		{ mode = { "n", "x" }, keys = "'" },
-- 		{ mode = { "n", "x" }, keys = "`" },
-- 		{ mode = { "n", "x" }, keys = '"' },
-- 		{ mode = { "i", "c" }, keys = "<C-r>" },
-- 		{ mode = "n", keys = "<C-w>" },
-- 		{ mode = { "n", "x" }, keys = "z" },
-- 	},
-- 	clues = {
-- 		miniclue.gen_clues.square_brackets(),
-- 		miniclue.gen_clues.builtin_completion(),
-- 		miniclue.gen_clues.g(),
-- 		miniclue.gen_clues.marks(),
-- 		miniclue.gen_clues.registers(),
-- 		miniclue.gen_clues.windows(),
-- 		miniclue.gen_clues.z(),
-- 	},
-- })
--
-- local MiniHipatterns = require("mini.hipatterns")
-- MiniHipatterns.setup({
-- 	highlighters = {
-- 		fixme = { pattern = "%f[%w]()FIXME()%f[%W]", group = "MiniHipatternsFixme" },
-- 		hack = { pattern = "%f[%w]()HACK()%f[%W]", group = "MiniHipatternsHack" },
-- 		todo = { pattern = "%f[%w]()TODO()%f[%W]", group = "MiniHipatternsTodo" },
-- 		note = { pattern = "%f[%w]()NOTE()%f[%W]", group = "MiniHipatternsNote" },
-- 		hex_color = MiniHipatterns.gen_highlighter.hex_color(),
-- 	},
-- })

-- require("mini.completion").setup({
-- 	lsp_completion = {
-- 		source_func = "omnifunc",
-- 		auto_setup = true,
-- 	},
-- })

-- local treesitter = require("nvim-treesitter")
-- treesitter.setup({
-- 	install_dir = vim.fs.joinpath(vim.fn.stdpath("data"), "site"),
-- })
--
-- local installed_parser = { "nix", "c", "lua", "vim", "vimdoc", "python", "toml", "json", "latex", "typst" }
-- treesitter.install(installed_parser, {})
--
-- vim.api.nvim_create_autocmd("FileType", {
-- 	pattern = installed_parser,
-- 	callback = function()
-- 		vim.treesitter.start()
-- 		vim.wo.foldexpr = "v:lua.vim.treesitter.foldexpr()"
-- 		vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
-- 		vim.o.foldmethod = "expr"
-- 	end,
-- })

-- local flake_path = 'builtins.getFlake "/Users/kei/dotfiles"'
--
-- vim.lsp.config("nixd", {
-- 	cmd = { "nixd" },
-- 	filetypes = { "nix" },
-- 	settings = {
-- 		nixd = {
-- 			formatting = {
-- 				command = { "nixfmt-rfc-style" },
-- 			},
-- 			options = {
-- 				nixpkgs = {
-- 					expr = string.format("import (%s).inputs.nixpkgs { }", flake_path),
-- 				},
-- 				nixos = {
-- 					expr = string.format("(%s).homeConfigurations.myHomeConfig.options", flake_path),
-- 				},
-- 				home_manager = {
-- 					expr = string.format(
-- 						"(%s).homeConfigurations.myHomeConfig.options.home-manager.users.type.getSubOptions []",
-- 						flake_path
-- 					),
-- 				},
-- 			},
-- 		},
-- 	},
-- })
-- vim.lsp.config("lua_ls", {
-- 	cmd = { "lua-language-server" },
-- 	filetypes = { "lua" },
-- 	settings = {
-- 		Lua = {
-- 			diagnostics = {
-- 				globals = { "vim", "hs", "wez" },
-- 			},
-- 			semantic = { enable = false },
-- 		},
-- 	},
-- })
--
-- vim.lsp.config("pyright", {
-- 	root_markers = { ".venv" },
-- 	settings = {
-- 		pyright = {
-- 			disableOrganizeImports = true,
-- 		},
-- 		python = {
-- 			analysis = {
-- 				ignore = { "*" },
-- 			},
-- 			venvPath = ".",
-- 			pythonPath = "./.venv/bin/python",
-- 		},
-- 	},
-- })
--
-- vim.lsp.config("denols", {
-- 	root_markers = { "deno.json" },
-- 	filetypes = { "typescript" },
-- 	init_options = {
-- 		lint = true,
-- 		unstable = false,
-- 		suggest = {
-- 			imports = {
-- 				hosts = {
-- 					["https://deno.land"] = true,
-- 					["https://cdn.nest.land"] = true,
-- 					["https://crux.land"] = true,
-- 				},
-- 			},
-- 		},
-- 	},
-- })
--
-- vim.lsp.config("ts_ls", {
-- 	filetypes = { "typescript" },
-- 	root_markers = { "package.json" },
-- })
--
-- vim.lsp.config("tinymist", {
-- 	cmd = { "tinymist" },
-- 	filetypes = { "typst" },
-- 	single_file_support = true,
-- })
--
-- vim.lsp.config("docker-language-server", {
-- 	cmd = { "docker-language-server", "start", "--stdio" },
-- 	filetypes = { "dockerfile", "yaml.docker-compose" },
-- 	get_language_id = function(_, ftype)
-- 		if ftype == "yaml.docker-compose" or ftype:lower():find("ya?ml") then
-- 			return "dockercompose"
-- 		else
-- 			return ftype
-- 		end
-- 	end,
-- 	root_markers = {
-- 		"Dockerfile",
-- 		"docker-compose.yaml",
-- 		"docker-compose.yml",
-- 		"compose.yaml",
-- 		"compose.yml",
-- 		"docker-bake.json",
-- 		"docker-bake.hcl",
-- 		"docker-bake.override.json",
-- 		"docker-bake.override.hcl",
-- 	},
-- })
--
-- vim.lsp.enable({
-- 	"lua_ls",
-- 	"ruff",
-- 	"ty",
-- 	"denols",
-- 	"ts_ls",
-- 	"rust_analyzer",
-- 	"copilot",
-- 	"nixd",
-- 	"texlab",
-- 	"tinymist",
-- 	"docker-language-server",
-- 	"yamlls",
-- 	"hls",
-- })
--
-- vim.diagnostic.config({
-- 	virtual_text = true,
-- })
--
-- vim.lsp.inline_completion.enable(true)
--
-- vim.api.nvim_create_autocmd("LspAttach", {
-- 	group = vim.api.nvim_create_augroup("UserLspConfig", {}),
-- 	callback = function(ev)
-- 		local opt = { noremap = true, silent = true, buffer = ev.buf }
-- 		vim.keymap.set("n", "gD", vim.lsp.buf.declaration, opt)
-- 		vim.keymap.set("n", "gd", vim.lsp.buf.definition, opt)
-- 		vim.keymap.set("n", "gi", vim.lsp.buf.implementation, opt)
-- 		vim.keymap.set("n", "gr", vim.lsp.buf.references, opt)
-- 		vim.keymap.set("n", "H", vim.lsp.buf.hover, opt)
-- 		vim.keymap.set("n", "K", vim.lsp.buf.type_definition, opt)
-- 		vim.keymap.set("n", "<Leader>D", vim.lsp.buf.type_definition, opt)
-- 		vim.keymap.set("n", "<Leader>rn", vim.lsp.buf.rename, opt)
-- 		vim.keymap.set("n", "<Leader>bf", "<cmd>lua vim.lsp.buf.format({async=true})<CR>", opt)
-- 		vim.keymap.set("n", "<Leader>ic", vim.lsp.buf.incoming_calls, opt)
-- 		vim.keymap.set("n", "[e", vim.diagnostic.goto_next, opt)
-- 		vim.keymap.set("n", "]e", vim.diagnostic.goto_prev, opt)
-- 		vim.keymap.set("n", "<Leader>e", vim.diagnostic.open_float, { noremap = true, silent = true })
-- 		vim.keymap.set("i", "<c-cr>", "<cmd>lua vim.lsp.inline_completion.get()<cr>", { silent = true })
--
-- 		local client = vim.lsp.get_client_by_id(ev.data.client_id)
-- 		if client and client.server_capabilities.documentHighlightProvider then
-- 			vim.api.nvim_command("set updatetime=100")
-- 			vim.api.nvim_create_augroup("lsp_document_highlight", { clear = true })
-- 			vim.api.nvim_clear_autocmds({
-- 				buffer = ev.buf,
-- 				group = "lsp_document_highlight",
-- 			})
-- 			vim.api.nvim_create_autocmd("CursorHold", {
-- 				callback = vim.lsp.buf.document_highlight,
-- 				buffer = ev.buf,
-- 				group = "lsp_document_highlight",
-- 				desc = "Document Highlight",
-- 			})
-- 			vim.api.nvim_create_autocmd("CursorMoved", {
-- 				callback = vim.lsp.buf.clear_references,
-- 				buffer = ev.buf,
-- 				group = "lsp_document_highlight",
-- 				desc = "Clear All the References",
-- 			})
-- 		end
-- 	end,
-- })

-- pcall(function()
-- 	require("conform").setup({
-- 		log_level = vim.log.levels.DEBUG,
-- 		formatters_by_ft = {
-- 			lua = { "stylua" },
-- 			nix = { "alejandra" },
-- 			python = { "ruff", "ruff_organize_imports", "ruff_format", "ruff_lint" },
-- 			rust = { "rustfmt", lsp_format = "fallback" },
-- 			javascript = { "prettierd", "prettier", stop_after_first = true },
-- 		},
-- 		format_on_save = {
-- 			timeout_ms = 500,
-- 			lsp_format = "fallback",
-- 		},
-- 	})
-- end)
--
-- local pick = require("mini.pick")
-- local extra = require("mini.extra")
--
-- pick.setup({})
-- extra.setup({})
-- vim.ui.select = pick.ui_select

-- vim.cmd.colorscheme("catppuccin-latte")

-- pcall(function()
-- 	require("nvim-lastplace").setup()
-- end)
-- pcall(function()
-- 	require("hlchunk").setup({
-- 		chunk = { enable = true },
-- 		indent = { enable = true },
-- 		line_num = { enable = true },
-- 		blank = { enable = true },
-- 	})
-- end)
-- pcall(function()
-- 	require("treesitter-context").setup({
-- 		enable = true,
-- 		min_window_height = 20,
-- 	})
-- end)
-- pcall(function()
-- 	require("nvim_context_vt").setup({ min_rows = 5 })
-- end)
-- pcall(function()
-- 	require("toggleterm").setup({
-- 		size = 100,
-- 		open_mapping = [[<c-t>]],
-- 		hide_numbers = true,
-- 		shade_filetypes = {},
-- 		shade_terminals = true,
-- 		shading_factor = 2,
-- 		start_in_insert = true,
-- 		insert_mappings = true,
-- 		persist_size = true,
-- 		direction = "float",
-- 		close_on_exit = true,
-- 	})
-- end)

-- vim.g.expand_region_text_objects = {
-- 	["iw"] = 0,
-- 	["iW"] = 0,
-- 	['i"'] = 0,
-- 	["ia"] = 0,
-- 	["i)"] = 1,
-- 	["il"] = 1,
-- 	["if"] = 1,
-- 	["af"] = 1,
-- 	["it"] = 1,
-- 	["ie"] = 0,
-- }
--
-- vim.g.silicon_options = {
-- 	font = "Cica",
-- 	no_line_number = false,
-- 	no_round_corner = true,
-- 	no_window_controls = true,
-- 	background_color = "#aaaaff",
-- 	line_offset = 1,
-- 	line_pad = 2,
-- 	pad_horiz = 80,
-- 	pad_vert = 100,
-- 	shadow_blur_radius = 0,
-- 	shadow_color = "#555555",
-- 	shadow_offset_x = 0,
-- 	shadow_offset_y = 0,
-- 	tab_width = 4,
-- 	theme = "Solarized (dark)",
-- }

-- pcall(function()
-- 	require("incline").setup({
-- 		render = function(props)
-- 			local buffullname = vim.api.nvim_buf_get_name(props.buf)
-- 			local bufname_t = vim.fn.fnamemodify(buffullname, ":t")
-- 			local bufname = (bufname_t and bufname_t ~= "") and bufname_t or "[No Name]"
-- 			local devicon = { " " }
-- 			local success, nvim_web_devicons = pcall(require, "nvim-web-devicons")
-- 			if success then
-- 				local bufname_r = vim.fn.fnamemodify(buffullname, ":r")
-- 				local bufname_e = vim.fn.fnamemodify(buffullname, ":e")
-- 				local base = (bufname_r and bufname_r ~= "") and bufname_r or bufname
-- 				local ext = (bufname_e and bufname_e ~= "") and bufname_e or vim.fn.fnamemodify(base, ":t")
-- 				local ic, hl = nvim_web_devicons.get_icon(base, ext, { default = true })
-- 				devicon = { ic, " ", group = hl }
-- 			end
-- 			local modified_icon = {}
-- 			if vim.api.nvim_get_option_value("modified", { buf = props.buf }) then
-- 				modified_icon = vim.tbl_extend("force", { "● " }, { guifg = "#968c81" })
-- 			end
-- 			local linenr = vim.api.nvim_win_get_cursor(0)[1]
-- 			return {
-- 				"l:" .. linenr,
-- 				" ",
-- 				devicon,
-- 				" ",
-- 				bufname,
-- 				" ",
-- 				modified_icon,
-- 			}
-- 		end,
-- 	})
-- end)

-- vim.api.nvim_create_autocmd("FileType", {
-- 	pattern = { "tex", "bib" },
-- 	callback = function()
-- 		if vim.fn.exists("*vimtex#complete#omnifunc") == 1 then
-- 			vim.opt_local.completefunc = "vimtex#complete#omnifunc"
-- 		end
-- 	end,
-- })

local ok_skel = pcall(require, "skkeleton")
if ok_skel then
	local userDict = "~/Library/Containers/net.mtgto.inputmethod.macSKK/Data/Documents/Dictionaries/skk-jisyo.utf8"
	vim.fn["skkeleton#azik#add_table"]("us")
	vim.fn["skkeleton#register_keymap"]("henkan", "X", "")
	vim.fn["skkeleton#register_keymap"]("input", "[", "katakana")
	vim.cmd([[
    call skkeleton#register_kanatable('rom', {
            \   ',': ['，', ''],
            \   '.': ['．', ''],
            \ })
  ]])
	vim.fn["skkeleton#config"]({
		kanaTable = "azik",
		sources = { "skk_dictionary", "skk_server" },
		userDictionary = userDict,
		globalDictionaries = {
			vim.fs.joinpath(vim.fn.expand("~/.skk-dict"), "SKK-JISYO.L"),
		},
		debug = false,
	})
end

-- local ok_ctx_vt, context_vt = pcall(require, "nvim_context_vt")
-- if ok_ctx_vt then
-- 	context_vt.setup({ min_rows = 5 })
-- end
