[[plugins]]
repo="maxmx03/solarized.nvim"
hook_add='''
colorscheme solarized
'''

# dot repeat
[[plugins]]
repo="tpope/vim-repeat"

# utility
[[plugins]]
repo="nvim-lua/plenary.nvim"

[[plugins]]
repo='nvim-tree/nvim-web-devicons'

[[plugins]]
repo="nvim-lualine/lualine.nvim"
hooks_file="$BASE_DIR/lua/lualine_config.lua"

[[plugins]]
repo="ethanholz/nvim-lastplace"
lua_source='''
require("nvim-lastplace").setup()
'''


# [[plugins]]
# repo="Shougo/deol.nvim"
# hooks_file='$BASE_DIR/rc/hooks/deol.lua'

# [[plugins]]
# repo = 'tani/dmacro.nvim'
# lua_add='''
# vim.keymap.set({ "i", "n" }, '<C-t>', '<Plug>(dmacro-play-macro)<CR>')
# '''
