[snippets]
include_default_snippets = true
custom_paths = []

[save]
autosave = "after_delay"
format_on_save = true
autosave_delay = 1000

[experimental]

[display]
theme = "light"
default_table_max_columns = 50
code_editor_font_size = 14
cell_output = "above"
default_width = "medium"
reference_highlighting = false
dataframes = "rich"
default_table_page_size = 10

[language_servers.ty]
enabled = true

[language_servers.pylsp]
enable_flake8 = false
enabled = true
enable_pylint = false
enable_mypy = true
enable_pydocstyle = false
enable_pyflakes = false
enable_ruff = true

[formatting]
line_length = 79

[server]
browser = "default"
follow_symlink = false

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[package_management]
manager = "pip"

[diagnostics]
enabled = true

[completion]
copilot = false
activate_on_typing = true

[runtime]
default_auto_download = []
reactive_tests = true
default_sql_output = "auto"
auto_reload = "off"
on_cell_change = "autorun"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
auto_instantiate = true
watcher_on_save = "lazy"

[ai]
mode = "manual"
rules = ""

[ai.open_ai]

[ai.bedrock]

[ai.google]

[ai.models]
displayed_models = []
custom_models = []

[ai.anthropic]
