[formatting]
line_length = 79

[server]
follow_symlink = false
browser = "default"

[experimental]

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = true

[diagnostics]
enabled = true

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[ai]
rules = ""
mode = "manual"

[ai.open_ai]

[ai.bedrock]

[ai.google]

[ai.anthropic]

[package_management]
manager = "pip"

[runtime]
watcher_on_save = "lazy"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
reactive_tests = true
auto_instantiate = true
default_sql_output = "auto"
auto_reload = "off"
default_auto_download = []
output_max_bytes = 8000000

[snippets]
custom_paths = []
include_default_snippets = true

[language_servers.ty]
enabled = true

[language_servers.pylsp]
enable_mypy = true
enable_flake8 = false
enable_pylint = false
enable_ruff = true
enabled = true
enable_pydocstyle = false
enable_pyflakes = false

[completion]
activate_on_typing = true
copilot = false

[display]
theme = "light"
default_table_max_columns = 50
code_editor_font_size = 14
dataframes = "rich"
cell_output = "above"
reference_highlighting = false
default_width = "medium"
default_table_page_size = 10
