[ai]
rules = ""
mode = "manual"

[ai.google]

[ai.anthropic]

[ai.bedrock]

[ai.open_ai]

[experimental]

[completion]
copilot = false
activate_on_typing = true

[snippets]
custom_paths = []
include_default_snippets = true

[server]
follow_symlink = false
browser = "default"

[display]
default_table_page_size = 10
default_table_max_columns = 50
theme = "light"
cell_output = "above"
code_editor_font_size = 14
dataframes = "rich"
reference_highlighting = false
default_width = "medium"

[runtime]
output_max_bytes = 8000000
default_sql_output = "auto"
auto_reload = "off"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
default_auto_download = []
auto_instantiate = true
watcher_on_save = "lazy"
reactive_tests = true

[formatting]
line_length = 79

[package_management]
manager = "pip"

[diagnostics]
enabled = true

[language_servers.ty]
enabled = true

[language_servers.pylsp]
enable_pyflakes = false
enable_ruff = true
enable_pydocstyle = false
enable_mypy = true
enable_pylint = false
enabled = true
enable_flake8 = false

[save]
format_on_save = true
autosave_delay = 1000
autosave = "after_delay"

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]
