name: update
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *
jobs:
  nix-update:
    name: Update lockfile
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    #   - name: Import GPG key
    #     uses: crazy-max/ghaction-import-gpg@v6
    #     with:
    #       gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
    #       passphrase: ${{ secrets.PASSPHRASE }}
    #       fingerprint: C0FD3B801CC6BCF942E61992163E8CC3BFEFF441
    #       git_user_signingkey: true
    #       git_commit_gpgsign: true
    #       git_config_global: true
      - uses: actions/checkout@v5
      - name: Setup nix
        uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run nvfetcher
        run: |
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          cd .config/nix
          nix run nixpkgs#nvfetcher
      - name: Run node2nix
        run: |
          cd .config/nix/node2nix/
          nix-shell -p nodePackages.node2nix --command "node2nix -i ./node-packages.json -o node-packages.nix"
      - name: Run flake update
        run: |
          cd .config/nix
          nix flake update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      # run: |
      #     cd .config/nix
      #     nix fmt
      # - name: Commit changes
      #   run: |
      #     git add .
      #     git commit -S -m "Update lockfile"
      #     git push origin HEAD
